### ISSUE TITLE
募集作成時にエラーが出る

### ISSUE THREAD

**Issue by kanatatsu64** [sansan-event-fusion/spark-2023-teamP-backend#7]
## ブランチ

develop

## 操作

```
POST /recruitments

{
    "userId": 1,
    "title": "test",
    "description": "test",
    "image": "test",
    "area": "test",
    "peopleLimit": 4,
    "targets": ["enjoy", "beginner"]
}
```

## 内容

railsのコンソールにエラーが出る。

```
web_1  | Started POST "/recruitments" for 172.23.0.1 at 2023-09-12 09:21:58 +0000
web_1  | Cannot render console from 172.23.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web_1  | Processing by RecruitmentsController#create as */*
web_1  |   Parameters: {"userId"=>1, "title"=>"test", "description"=>"test", "image"=>"test", "area"=>"test", "peopleLimit"=>4, "targets"=>["enjoy", "beginner"], "recruitment"=>{"title"=>"test", "description"=>"test", "image"=>"test", "area"=>"test"}}
web_1  | Unpermitted parameters: :targets, :recruitment. Context: { controller: RecruitmentsController, action: create, request: #<ActionDispatch::Request:0x00007f88e11debf8>, params: {"userId"=>1, "title"=>"test", "description"=>"test", "image"=>"test", "area"=>"test", "peopleLimit"=>4, "targets"=>["enjoy", "beginner"], "controller"=>"recruitments", "action"=>"create", "recruitment"=>{"title"=>"test", "description"=>"test", "image"=>"test", "area"=>"test"}} }
web_1  |   TRANSACTION (1.0ms)  BEGIN
web_1  |   ↳ app/controllers/recruitments_controller.rb:14:in `create'
web_1  |   User Load (1.2ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
web_1  |   ↳ app/controllers/recruitments_controller.rb:14:in `create'
web_1  |   Recruitment Create (5.2ms)  INSERT INTO `recruitments` (`user_id`, `title`, `description`, `image`, `area`, `people_limit`, `participants_count`, `created_at`, `updated_at`) VALUES (1, 'test', 'test', NULL, 'test', 4, 0, '2023-09-12 09:21:59.066512', '2023-09-12 09:21:59.066512')
web_1  |   ↳ app/controllers/recruitments_controller.rb:14:in `create'
web_1  |   TRANSACTION (0.8ms)  ROLLBACK
web_1  |   ↳ app/controllers/recruitments_controller.rb:14:in `create'
web_1  | Completed 500 Internal Server Error in 51ms (ActiveRecord: 8.3ms | Allocations: 4439)
web_1  |
web_1  |
web_1  |
web_1  | ActiveRecord::NotNullViolation (Mysql2::Error: Column 'image' cannot be null):
web_1  |
web_1  | app/controllers/recruitments_controller.rb:14:in `create'
```

**Comment by kanatatsu64** [comment]
`image`をフォームの画像にする。
